Revert "Generic handling for ROMs with custom Resources subclasses"
This reverts commit b24be5d2b929be45a79ec14256939e87d198b5ba.

This commit caused Nova Launcher to crash

>>>
FATAL EXCEPTION: launcher-loader
Process: com.teslacoilsw.launcher, PID: 13668
java.lang.RuntimeException: java.security.NoSuchAlgorithmException: MessageDigest MD5 implementation not found
  at com.android.org.bouncycastle.crypto.digests.OpenSSLDigest.<init>(OpenSSLDigest.java:38)
  at com.android.org.bouncycastle.crypto.digests.OpenSSLDigest$MD5.<init>(OpenSSLDigest.java:75)
...
Caused by: java.security.NoSuchAlgorithmException: MessageDigest MD5 implementation not found
at org.apache.harmony.security.fortress.Engine.notFound(Engine.java)
at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java)
...

It looks like org.apache.harmony.security.fortress.Services class has trouble
with a method called initServiceInfo(Provider) because MD5 implementation was not found.
And there we have checkMDPP(Provider) in it so I thought that it has something to do with
SamsungHelper.hookMdpp() which is found in wanam's XposedBridge.
I thought that it's maybe a classLoader related problem or some kind of timing problem.
Further research is required but I just revert this commit instead because
I only target Samsung Lollipop sdk21 devices.